<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTgT9ULj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTgT9ULj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTgT9ULj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTgT9ULj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTgT9ULj\App_KernelDevDebugContainer([
    'container.build_hash' => 'TgT9ULj',
    'container.build_id' => '2c9f72b7',
    'container.build_time' => 1701136664,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTgT9ULj');
