framework:
    # ...
    session:
        # ...
        gc_maxlifetime: 3600

gregwar_captcha:
    width: 150
    height: 40
    quality: 90
    as_file: false
    charset: "0123456789"
    length: 6
    gc_freq: 5
    keep_value: false
    distortion: true
    invalid_message: "Incorrect captcha code!"
